-- GENERATED by scripts/record-migrations.mjs (npm run migrations:record). Do not edit by hand.
--
-- Run this ONCE in the Supabase SQL Editor, after every file in supabase/migrations has been
-- applied, if the database was built by pasting migrations by hand. It tells the Supabase CLI
-- they are already applied, so `supabase db push` will not try to run them again.
--
-- Safe to run again at any time: rows that already exist are skipped. After applying a new
-- migration by hand, run `npm run migrations:record` and paste the file again.

create schema if not exists supabase_migrations;

create table if not exists supabase_migrations.schema_migrations (
  version text not null primary key,
  statements text[],
  name text
);

insert into supabase_migrations.schema_migrations (version, name, statements) values
  ('20260926091436', 'bc46e408-4992-4b3f-8822-fd5f0953de11', '{}'),
  ('20260926094840', '15fad0dc-8247-466c-88a3-a2964158a512', '{}'),
  ('20260926100803', '67fe74bb-d6f2-41dc-ba45-7780f8bb32c1', '{}'),
  ('20260926104006', 'c2bb3c1c-4506-4dfe-8ed0-3a8a9929c0af', '{}'),
  ('20260926195052', 'fcbfd618-335e-4c4c-9beb-079463c42a89', '{}'),
  ('20260926200756', 'b7cf29dc-8c46-4bda-8860-717cd18a558e', '{}'),
  ('20260926201053', '5b26d1fd-e485-4904-94f7-5b7d95b67539', '{}'),
  ('20260926202320', '45f232ed-f815-4661-875a-8693c1d36f8f', '{}'),
  ('20260928075759', 'be20b4ae-41fe-42ab-9795-5a185553ae48', '{}'),
  ('20260928084213', '98dcd038-4994-452d-94ef-9b325160d4fe', '{}'),
  ('20260928094830', 'ac67668a-b811-4d74-bd89-723ab3162ac0', '{}'),
  ('20260928095305', '22d03238-fc9b-4ce1-abb7-c69dd2b8122f', '{}'),
  ('20260928100924', '8f2fc5da-5d79-4660-9548-cbdfcc4bce19', '{}'),
  ('20260928105702', '4c122731-62a8-4fab-852c-6f8da6aa8b81', '{}'),
  ('20260928120303', '19e640dc-427a-4f64-920e-320f14b0486b', '{}'),
  ('20260928120317', '362f320a-d07f-4d17-a9fb-f27b1967f09c', '{}'),
  ('20260928123008', '5a7aac0a-a143-4fd1-96ca-64b9c969722f', '{}'),
  ('20261005120000', 'standalone_api', '{}'),
  ('20261005130000', 'seed_exercise_library', '{}'),
  ('20261006120000', 'protect_finished_sets', '{}'),
  ('20261006140000', 'index_exercise_history', '{}'),
  ('20261006150000', 'finish_at_last_set', '{}'),
  ('20261007120000', 'equipment_aware_swaps_and_barbell_plan', '{}'),
  ('20261007130000', 'revoke_members_update_on_users', '{}'),
  ('20261007140000', 'refinish_attaches_extra_sets', '{}'),
  ('20261007150000', 'update_training_profile', '{}'),
  ('20261007160000', 'beta_testers', '{}'),
  ('20261008120000', 'weight_unit', '{}')
on conflict (version) do nothing;
