ALTER TABLE public.exercises ADD COLUMN setup_cue text, ADD COLUMN position_cue text, ADD COLUMN movement_cue text;
UPDATE public.exercises AS e SET setup_cue=v.setup, position_cue=v.position, movement_cue=v.movement
FROM (VALUES
('back-extension','Set the pad just below your hips.','Cross arms, brace your core and keep spine neutral.','Hinge down, then rise only until your body is straight.'),
('barbell-hip-thrust','Pad the bar and place your upper back on a bench.','Feet flat, knees bent, bar centered over hips.','Drive through your heels and squeeze glutes at the top.'),
('barbell-rdl','Load a light bar and stand with feet hip-width.','Hold the bar close to thighs; soften your knees.','Push hips back, keep back flat, then drive hips forward.'),
('db-rdl','Choose light dumbbells and stand hip-width.','Hold weights in front of thighs with soft knees.','Hinge back with weights close; stand by squeezing glutes.'),
('lying-leg-curl','Set the ankle pad just above your heels.','Lie face down with hips pressed into the bench.','Curl heels toward glutes; lower slowly without lifting hips.'),
('bench-press','Set a manageable bar weight and safety supports.','Eyes under bar, feet flat, shoulder blades tucked.','Lower to mid-chest, then press up and slightly back.'),
('chest-press','Adjust seat until handles sit at mid-chest.','Feet flat, back on pad, wrists straight.','Press forward without locking elbows; return slowly.'),
('db-bench','Choose light dumbbells and a flat bench.','Feet flat, weights beside chest, blades tucked.','Press above chest; lower with elbows about 45 degrees out.'),
('incline-db-press','Set the bench to about 30 degrees.','Feet flat, dumbbells at chest, back supported.','Press up over shoulders; lower slowly without flaring elbows.'),
('pec-fly','Set seat so handles align with your chest.','Sit tall, feet flat and elbows slightly bent.','Hug handles together; open slowly without over-stretching.'),
('barbell-row','Choose a light bar and stand hip-width.','Hinge to about 45 degrees with a flat back.','Pull bar to lower ribs; lower without swinging.'),
('chest-supported-row','Adjust seat so chest rests on the pad.','Feet planted, chest against pad, arms extended.','Drive elbows behind torso; pause, then release slowly.'),
('db-rear-delt-fly','Pick very light dumbbells.','Hinge forward, keep back flat and elbows soft.','Raise arms wide; squeeze upper back without shrugging.'),
('db-row','Place one hand and knee on a sturdy bench.','Keep back flat and the other foot planted.','Pull dumbbell toward hip; lower fully without twisting.'),
('seated-row','Set a comfortable cable weight and handle.','Sit tall, knees soft and feet braced.','Pull to your stomach; squeeze shoulder blades, then extend.'),
('back-squat','Set rack hooks near shoulder height and use safeties.','Bar on upper back, feet shoulder-width, core braced.','Sit down and back; drive up through mid-foot.'),
('db-split-squat','Set rear foot on a stable low bench.','Front foot planted, dumbbells by your sides.','Drop back knee down; push through front heel to rise.'),
('goblet-squat','Hold a light dumbbell upright at your chest.','Feet shoulder-width, chest tall and core braced.','Squat between knees; push through whole foot to stand.'),
('hack-squat','Set shoulder pads and choose a light load.','Back flat on pad, feet shoulder-width on platform.','Lower with control; press up through heels without locking knees.'),
('leg-press','Set seat and a light load; release safety handles.','Feet hip-width mid-platform, lower back on pad.','Lower to comfortable depth; press without locking knees.'),
('arnold-press','Choose light dumbbells and a supported seat.','Weights at chin height, palms facing you, core braced.','Rotate palms outward while pressing; reverse slowly.'),
('db-shoulder-press','Choose light dumbbells and a supported seat.','Feet flat, weights beside ears, back against seat.','Press up without arching your back; lower to ear height.'),
('landmine-press','Secure the bar end and start with a light load.','Hold bar at shoulder, stagger feet and brace core.','Press up and forward while keeping ribs down.'),
('overhead-press','Set a light bar at collarbone height.','Feet hip-width, glutes squeezed and wrists stacked.','Press vertically; move head through under bar at top.'),
('shoulder-press-machine','Set seat so handles begin at shoulder height.','Feet flat, back against pad and ribs down.','Press overhead without shrugging; lower slowly.'),
('assisted-pullup','Choose assistance weight and grip the handles.','Knees on pad, core braced and shoulders down.','Pull chin above bar; lower with control.'),
('close-grip-pulldown','Attach V-handle and choose a light weight.','Sit tall with thighs secured under pads.','Pull to upper chest with elbows down; extend fully.'),
('db-pullover','Choose a light dumbbell and a stable bench.','Lie supported, hold weight above chest, elbows soft.','Lower behind head only as comfortable; pull back over chest.'),
('lat-pulldown','Choose a light weight and adjust thigh pads.','Grip just wider than shoulders; sit tall.','Lead with elbows to upper chest; return slowly.'),
('resistance-band-pull','Anchor the band securely above head height.','Sit or kneel tall, hold band and brace core.','Drive elbows down to sides; return slowly.')
) AS v(id, setup, position, movement) WHERE e.id=v.id;