-- Full exercise library and pre-made plans, exported from the original database.
-- Twelve exercises were added outside migrations there, so a fresh database needs
-- this to match. Safe to re-run: rows are upserted.

INSERT INTO public.exercises (id, name, movement_type, equipment_type, target, instructions, setup_cue, position_cue, movement_cue, video_url, alternative_exercise_id) VALUES
  ('arnold-press', 'Arnold Press', 'Vertical Press', 'Dumbbell', '3 Sets x 10-12 Reps', 'Start palms facing you at chin height. Rotate palms forward as you press overhead, reverse on the way down.', 'Choose light dumbbells and a supported seat.', 'Weights at chin height, palms facing you, core braced.', 'Rotate palms outward while pressing; reverse slowly.', NULL, 'shoulder-press-machine'),
  ('assisted-pullup', 'Assisted Pull-Up', 'Vertical Pull', 'Machine', '3 Sets x 8-10 Reps', 'Knees on the pad, overhand grip. Pull chin above the bar, lower all the way with control.', 'Choose assistance weight and grip the handles.', 'Knees on pad, core braced and shoulders down.', 'Pull chin above bar; lower with control.', NULL, 'lat-pulldown'),
  ('back-extension', '45° Back Extension', 'Hinge', 'Machine', '3 Sets x 12-15 Reps', 'Hips on the pad, arms crossed. Hinge down with a neutral spine, then raise until body forms a straight line.', 'Set the pad just below your hips.', 'Cross arms, brace your core and keep spine neutral.', 'Hinge down, then rise only until your body is straight.', NULL, 'db-rdl'),
  ('back-squat', 'Barbell Back Squat', 'Squat', 'Barbell', '3 Sets x 8-10 Reps', 'Bar on upper back, feet shoulder-width. Sit hips down and back until thighs are parallel, then drive up through mid-foot.', 'Set rack hooks near shoulder height and use safeties.', 'Bar on upper back, feet shoulder-width, core braced.', 'Sit down and back; drive up through mid-foot.', NULL, 'goblet-squat'),
  ('barbell-curl', 'Barbell Biceps Curl', 'Arms/Core', 'Barbell', '3 Sets x 10-12 Reps', 'Curl the barbell to your chest with control.', 'Load a light bar or use an EZ-bar with small plates.', 'Grip shoulder-width, stand tall, elbows by your sides.', 'Curl without leaning back, pause at the top, lower slowly.', NULL, 'db-curl'),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'Hinge', 'Barbell', '3 Sets x 10-12 Reps', 'Upper back on a bench, bar padded over hips. Drive hips up until body is flat, pause and squeeze glutes.', 'Pad the bar and place your upper back on a bench.', 'Feet flat, knees bent, bar centered over hips.', 'Drive through your heels and squeeze glutes at the top.', NULL, 'back-extension'),
  ('barbell-rdl', 'Barbell Romanian Deadlift', 'Hinge', 'Barbell', '3 Sets x 8-10 Reps', 'Soft knees, bar close to legs. Push hips back until you feel a hamstring stretch, then squeeze glutes to stand.', 'Load a light bar and stand with feet hip-width.', 'Hold the bar close to thighs; soften your knees.', 'Push hips back, keep back flat, then drive hips forward.', NULL, 'db-rdl'),
  ('barbell-row', 'Barbell Bent-Over Row', 'Horizontal Pull', 'Barbell', '3 Sets x 8-10 Reps', 'Hinge to 45 degrees, flat back. Pull bar to lower ribs, squeeze shoulder blades, lower under control.', 'Choose a light bar and stand hip-width.', 'Hinge to about 45 degrees with a flat back.', 'Pull bar to lower ribs; lower without swinging.', NULL, 'db-row'),
  ('bench-press', 'Barbell Bench Press', 'Horizontal Press', 'Barbell', '3 Sets x 8-10 Reps', 'Eyes under the bar, shoulder blades pinched. Lower to mid-chest, press up and slightly back.', 'Set a manageable bar weight and safety supports.', 'Eyes under bar, feet flat, shoulder blades tucked.', 'Lower to mid-chest, then press up and slightly back.', NULL, 'db-bench'),
  ('cable-crunch', 'Kneeling Cable Crunch', 'Arms/Core', 'Machine', '3 Sets x 12-15 Reps', 'Crunch your ribs toward your hips against the cable.', 'Set the pulley high with a rope attachment and a light weight.', 'Kneel facing the stack, rope beside your head, hips still.', 'Round your back to curl down using your abs, pause, rise slowly.', NULL, 'cable-pushdown'),
  ('cable-pushdown', 'Cable Triceps Pushdown', 'Arms/Core', 'Machine', '3 Sets x 10-12 Reps', 'Push the cable handle down until your arms are straight.', 'Set the pulley to the top and attach a rope or straight bar.', 'Stand close, slight forward lean, elbows tucked at your ribs.', 'Press down until arms lock out, keep elbows still, return slowly.', NULL, 'db-curl'),
  ('chest-press', 'Chest Press Machine', 'Horizontal Press', 'Machine', '3 Sets x 10-12 Reps', 'Handles at mid-chest height. Press forward without locking elbows, return slowly keeping back on the pad.', 'Adjust seat until handles sit at mid-chest.', 'Feet flat, back on pad, wrists straight.', 'Press forward without locking elbows; return slowly.', NULL, 'pec-fly'),
  ('chest-supported-row', 'Chest-Supported Machine Row', 'Horizontal Pull', 'Machine', '3 Sets x 10-12 Reps', 'Chest on the pad. Pull handles back driving elbows past your torso, pause, release slowly.', 'Adjust seat so chest rests on the pad.', 'Feet planted, chest against pad, arms extended.', 'Drive elbows behind torso; pause, then release slowly.', NULL, 'db-row'),
  ('close-grip-pulldown', 'Close-Grip Pulldown', 'Vertical Pull', 'Machine', '3 Sets x 10-12 Reps', 'V-handle attachment. Pull to upper chest keeping torso tall, squeeze lats and extend fully.', 'Attach V-handle and choose a light weight.', 'Sit tall with thighs secured under pads.', 'Pull to upper chest with elbows down; extend fully.', NULL, 'assisted-pullup'),
  ('db-bench', 'Dumbbell Bench Press', 'Horizontal Press', 'Dumbbell', '3 Sets x 10-12 Reps', 'Lie flat, dumbbells at chest level. Press up until arms are straight, lower slowly with elbows at 45 degrees.', 'Choose light dumbbells and a flat bench.', 'Feet flat, weights beside chest, blades tucked.', 'Press above chest; lower with elbows about 45 degrees out.', NULL, 'chest-press'),
  ('db-curl', 'Dumbbell Biceps Curl', 'Arms/Core', 'Dumbbell', '3 Sets x 10-12 Reps', 'Curl the dumbbells up with control, then lower slowly.', 'Pick a pair of light dumbbells you can curl 12 times cleanly.', 'Stand tall, elbows pinned to your sides, palms facing forward.', 'Curl up without swinging, squeeze at the top, lower for 3 seconds.', NULL, 'barbell-curl'),
  ('db-pullover', 'Dumbbell Pullover', 'Vertical Pull', 'Dumbbell', '3 Sets x 10-12 Reps', 'Lie across a bench holding one dumbbell over chest. Lower it behind your head with soft elbows, pull back over.', 'Choose a light dumbbell and a stable bench.', 'Lie supported, hold weight above chest, elbows soft.', 'Lower behind head only as comfortable; pull back over chest.', NULL, 'lat-pulldown'),
  ('db-rdl', 'Dumbbell Romanian Deadlift', 'Hinge', 'Dumbbell', '3 Sets x 10-12 Reps', 'Dumbbells in front of thighs. Hinge at hips with a flat back, lower to mid-shin, drive hips forward to stand.', 'Choose light dumbbells and stand hip-width.', 'Hold weights in front of thighs with soft knees.', 'Hinge back with weights close; stand by squeezing glutes.', NULL, 'barbell-rdl'),
  ('db-rear-delt-fly', 'Dumbbell Rear Delt Fly', 'Horizontal Pull', 'Dumbbell', '3 Sets x 12-15 Reps', 'Hinge forward, light dumbbells hanging. Raise arms out wide with soft elbows, squeeze upper back.', 'Pick very light dumbbells.', 'Hinge forward, keep back flat and elbows soft.', 'Raise arms wide; squeeze upper back without shrugging.', NULL, 'chest-supported-row'),
  ('db-row', 'Dumbbell Row', 'Horizontal Pull', 'Dumbbell', '3 Sets x 10-12 Reps / arm', 'Hand and knee on a bench. Pull the dumbbell to your hip, keep elbow close, lower fully.', 'Place one hand and knee on a sturdy bench.', 'Keep back flat and the other foot planted.', 'Pull dumbbell toward hip; lower fully without twisting.', NULL, 'seated-row'),
  ('db-shoulder-press', 'Dumbbell Shoulder Press', 'Vertical Press', 'Dumbbell', '3 Sets x 10-12 Reps', 'Seated, dumbbells at ear height. Press up until arms are straight, lower to ear level with control.', 'Choose light dumbbells and a supported seat.', 'Feet flat, weights beside ears, back against seat.', 'Press up without arching your back; lower to ear height.', NULL, 'shoulder-press-machine'),
  ('db-split-squat', 'Dumbbell Bulgarian Split Squat', 'Squat', 'Dumbbell', '3 Sets x 8-10 Reps / leg', 'Rear foot on a bench, dumbbells at sides. Drop the back knee straight down, drive up through the front heel.', 'Set rear foot on a stable low bench.', 'Front foot planted, dumbbells by your sides.', 'Drop back knee down; push through front heel to rise.', NULL, 'hack-squat'),
  ('goblet-squat', 'Goblet Squat', 'Squat', 'Dumbbell', '3 Sets x 10-12 Reps', 'Hold one dumbbell at your chest. Squat between your knees keeping elbows inside knees and chest tall.', 'Hold a light dumbbell upright at your chest.', 'Feet shoulder-width, chest tall and core braced.', 'Squat between knees; push through whole foot to stand.', NULL, 'leg-press'),
  ('hack-squat', 'Hack Squat Machine', 'Squat', 'Machine', '3 Sets x 10-12 Reps', 'Back flat on the pad, feet shoulder-width. Lower under control to 90 degrees and press up through heels.', 'Set shoulder pads and choose a light load.', 'Back flat on pad, feet shoulder-width on platform.', 'Lower with control; press up through heels without locking knees.', NULL, 'back-squat'),
  ('incline-db-press', 'Incline Dumbbell Press', 'Horizontal Press', 'Dumbbell', '3 Sets x 10-12 Reps', 'Set bench to 30 degrees. Press weights straight up over shoulders keeping chest packed.', 'Set the bench to about 30 degrees.', 'Feet flat, dumbbells at chest, back supported.', 'Press up over shoulders; lower slowly without flaring elbows.', NULL, 'chest-press'),
  ('landmine-press', 'Landmine Press', 'Vertical Press', 'Barbell', '3 Sets x 10 Reps / arm', 'Hold the bar end at your shoulder, staggered stance. Press up and forward, keeping ribs down.', 'Secure the bar end and start with a light load.', 'Hold bar at shoulder, stagger feet and brace core.', 'Press up and forward while keeping ribs down.', NULL, 'arnold-press'),
  ('lat-pulldown', 'Lat Pulldown', 'Vertical Pull', 'Machine', '3 Sets x 10-12 Reps', 'Grip slightly wider than shoulders. Pull the bar to upper chest leading with elbows, return slowly.', 'Choose a light weight and adjust thigh pads.', 'Grip just wider than shoulders; sit tall.', 'Lead with elbows to upper chest; return slowly.', NULL, 'resistance-band-pull'),
  ('leg-press', 'Leg Press', 'Squat', 'Machine', '3 Sets x 10-12 Reps', 'Feet hip-width mid-platform. Lower until knees reach 90 degrees, press back without locking knees.', 'Set seat and a light load; release safety handles.', 'Feet hip-width mid-platform, lower back on pad.', 'Lower to comfortable depth; press without locking knees.', NULL, 'goblet-squat'),
  ('lying-leg-curl', 'Lying Leg Curl Machine', 'Hinge', 'Machine', '3 Sets x 10-12 Reps', 'Pad just above heels, hips pressed down. Curl heels toward glutes, lower slowly over 3 seconds.', 'Set the ankle pad just above your heels.', 'Lie face down with hips pressed into the bench.', 'Curl heels toward glutes; lower slowly without lifting hips.', NULL, 'db-rdl'),
  ('overhead-press', 'Barbell Overhead Press', 'Vertical Press', 'Barbell', '3 Sets x 8-10 Reps', 'Bar at collarbone, glutes tight. Press straight overhead moving your head back then through under the bar.', 'Set a light bar at collarbone height.', 'Feet hip-width, glutes squeezed and wrists stacked.', 'Press vertically; move head through under bar at top.', NULL, 'db-shoulder-press'),
  ('pec-fly', 'Pec Fly Machine', 'Horizontal Press', 'Machine', '3 Sets x 12-15 Reps', 'Seat so handles are at chest height. Soft elbows, bring handles together in a hugging arc, open slowly.', 'Set seat so handles align with your chest.', 'Sit tall, feet flat and elbows slightly bent.', 'Hug handles together; open slowly without over-stretching.', NULL, 'incline-db-press'),
  ('resistance-band-pull', 'Resistance Band Pull', 'Vertical Pull', 'Dumbbell', '3 Sets x 12-15 Reps', 'Anchor the band high. Pull down to your chest, driving elbows to your sides, return slowly.', 'Anchor the band securely above head height.', 'Sit or kneel tall, hold band and brace core.', 'Drive elbows down to sides; return slowly.', NULL, 'lat-pulldown'),
  ('seated-row', 'Seated Cable Row', 'Horizontal Pull', 'Machine', '3 Sets x 10-12 Reps', 'Sit tall, knees soft. Pull the handle to your stomach, squeeze shoulder blades, extend arms slowly.', 'Set a comfortable cable weight and handle.', 'Sit tall, knees soft and feet braced.', 'Pull to your stomach; squeeze shoulder blades, then extend.', NULL, 'db-row'),
  ('shoulder-press-machine', 'Machine Shoulder Press', 'Vertical Press', 'Machine', '3 Sets x 10-12 Reps', 'Handles at shoulder height, back on the pad. Press up without shrugging, lower slowly.', 'Set seat so handles begin at shoulder height.', 'Feet flat, back against pad and ribs down.', 'Press overhead without shrugging; lower slowly.', NULL, 'db-shoulder-press')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  movement_type = EXCLUDED.movement_type,
  equipment_type = EXCLUDED.equipment_type,
  target = EXCLUDED.target,
  instructions = EXCLUDED.instructions,
  setup_cue = EXCLUDED.setup_cue,
  position_cue = EXCLUDED.position_cue,
  movement_cue = EXCLUDED.movement_cue,
  video_url = EXCLUDED.video_url,
  alternative_exercise_id = EXCLUDED.alternative_exercise_id;

INSERT INTO public.workout_programs (id, equipment_type, day_number, exercise_ids_list, target_sets, target_reps) VALUES
  ('48dd5db8-d65d-46f5-8c49-628ee258455c', 'barbell', 1, ARRAY['back-squat', 'bench-press', 'barbell-row']::text[], 3, 10),
  ('5ec35019-550b-4039-858e-2404c3590f54', 'barbell', 2, ARRAY['barbell-rdl', 'overhead-press', 'db-pullover']::text[], 3, 10),
  ('9d23bdfa-f785-466a-ac9a-1d369cf8a9c8', 'barbell', 3, ARRAY['db-split-squat', 'incline-db-press', 'barbell-curl']::text[], 3, 10),
  ('e8eb783a-4d20-4954-b3c9-777a9675cd3f', 'dumbbells', 1, ARRAY['goblet-squat', 'db-bench', 'db-row']::text[], 3, 10),
  ('16eda9a5-4f97-46c0-b2e8-4c769b944c55', 'dumbbells', 2, ARRAY['db-rdl', 'db-shoulder-press', 'db-pullover']::text[], 3, 10),
  ('629aacf1-8f61-45f9-b029-acd22f8e464c', 'dumbbells', 3, ARRAY['db-split-squat', 'incline-db-press', 'db-curl']::text[], 3, 10),
  ('d1974f6c-c09b-46a8-b277-0d7354679732', 'full-gym', 1, ARRAY['goblet-squat', 'chest-press', 'seated-row', 'back-extension']::text[], 3, 10),
  ('0799f209-c536-4d19-b9d0-7522e0e10e67', 'full-gym', 2, ARRAY['db-rdl', 'shoulder-press-machine', 'lat-pulldown', 'lying-leg-curl']::text[], 3, 10),
  ('69bb8623-f072-423c-89d4-2d4865bbd863', 'full-gym', 3, ARRAY['leg-press', 'incline-db-press', 'db-curl', 'cable-pushdown', 'cable-crunch']::text[], 3, 10)
ON CONFLICT (equipment_type, day_number) DO UPDATE SET
  exercise_ids_list = EXCLUDED.exercise_ids_list,
  target_sets = EXCLUDED.target_sets,
  target_reps = EXCLUDED.target_reps;
